//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViajeTerminal
    {
        public int CodigoInterno { get; set; }
        public string CodigoTerminal { get; set; }
        public int NroParada { get; set; }
    
        public virtual Terminales Terminales { get; set; }
    }
}
